def drawone():
   
    import turtle
    akagami = turtle.Turtle()
    akagami.speed(10)
    my_turtle_screen = turtle.Screen()
    y_coordinate = -125
    def draw_circle_on_top_of_stick(fill_color, border_color, x, y, radius):
        akagami.penup()
        akagami.pensize(3)
        akagami.color(fill_color)
        akagami.fillcolor(border_color)
        akagami.goto(x, y)
        akagami.pendown()
        akagami.begin_fill()
        akagami.circle(radius)
        akagami.end_fill()
        akagami.getscreen().update()
    def draw_candle_for_cake(fill_color, border_color, x, y):
        akagami.penup()        
        akagami.color(border_color)       
        akagami.fillcolor(fill_color)
        akagami.goto(x, y)
        akagami.pendown()
        akagami.begin_fill() 
        akagami.forward(25)
        akagami.left(90)
        akagami.forward(60)
        akagami.left(90)
        akagami.forward(25)
        akagami.left(90)
        akagami.forward(60)
        akagami.left(90)
        akagami.end_fill()        
        akagami.getscreen().update()

    def draw_stick_on_candle(fill_color, x, y, cursor_size):
        akagami.penup()
        akagami.color(fill_color)
        akagami.fillcolor(fill_color)
        akagami.goto(x, y)
        akagami.pensize(cursor_size)
        akagami.begin_fill()
        akagami.pendown()
        akagami.right(90)
        akagami.forward(12)
        akagami.end_fill()
        akagami.getscreen().update()

    def write_happy_inside_circle(text_color, x, y):
        akagami.penup()
        akagami.color(text_color)
        akagami.goto(x, y)
        akagami.begin_fill()
        akagami.pendown()
        akagami.write("Happy Birthday", font=("sans-serif", 16, "bold"))
        akagami.getscreen().update()

    def write_birthday_inside_circle(text_color, x, y):
        akagami.penup()
        akagami.color(text_color)
        akagami.goto(x, y)
        akagami.begin_fill()
        akagami.pendown()
        akagami.write("Luffy🥳🎂", font=("sans-serif", 26, "bold"))
        akagami.getscreen().update()

    def draw_stick(fill_color, border_color, x, y):
        akagami.penup()
        akagami.pensize(3)
        akagami.color(border_color)
        akagami.fillcolor(fill_color)
        akagami.goto(x, y)
        akagami.begin_fill()
        akagami.pendown()
        akagami.left(180)
        akagami.forward(200)
        akagami.end_fill()
        akagami.getscreen().update()

    def draw_toppings_on_cake(fill_color, border_color, x, y, radius):
        akagami.penup()
        akagami.color(border_color)
        akagami.fillcolor(fill_color)
        akagami.goto(x, y)
        akagami.pendown()
        akagami.begin_fill()
        akagami.forward(10)
        akagami.left(90)
        akagami.circle(radius, extent = 180)
        akagami.left(90)
        akagami.forward(10)
        akagami.end_fill()
        akagami.getscreen().update()

    def draw_layer_of_the_cake(fill_color, border_color, cursor_size, x, y, width, height):
        akagami.hideturtle()
        akagami.penup()
        akagami.pensize(cursor_size)
        akagami.color(border_color)
        akagami.fillcolor(fill_color)
        akagami.goto(x, y)
        akagami.pendown()
        akagami.begin_fill()

        for i in range(2):
            akagami.forward(width)
            akagami.left(90)
            akagami.forward(height)
            akagami.left(90)
        akagami.end_fill()
        akagami.setheading(0)
        akagami.getscreen().update()
    my_turtle_screen.bgcolor("white")
    parts_of_cake = []
    parts_of_cake.append(["#A020F0", "#000000", 3, 30])
    parts_of_cake.append(["#55FF55", "#000000", 3, 20])
    parts_of_cake.append(["#B87333", "#000000", 3, 60])
    draw_layer_of_the_cake("#FFC0CB", "#000000", 3, -220, y_coordinate - 70, 400, 10)
    for parts in parts_of_cake:
        draw_layer_of_the_cake(parts[0], parts[1], parts[2], -135, y_coordinate - 60, 240, parts[3])
        y_coordinate += parts[3]
    draw_toppings_on_cake("#C20067", "#000000", -120, y_coordinate - 60, 10)
    draw_toppings_on_cake("#FFFF00", "#000000", -80, y_coordinate - 60, 10)
    draw_toppings_on_cake("#FF0000", "#000000", 25, y_coordinate - 60, 10)
    draw_toppings_on_cake("#0000FF", "#000000", 59, y_coordinate - 60, 10)
    draw_candle_for_cake("#FFF44F", "#000000", -40, y_coordinate - 60)
    draw_stick_on_candle("#181A18", -26, y_coordinate + 15, 7)
    draw_stick("#181A18", "#181A18", 0, y_coordinate - 60)
    draw_circle_on_top_of_stick("#181A18", "#FFFDD0", 100, y_coordinate + 235, 100)
    write_happy_inside_circle("#000000", -70, y_coordinate + 240)
    write_birthday_inside_circle("#000000", -80, y_coordinate + 190)
    my_turtle_screen.exitonclick()
   
